### ISSUE TITLE
replicas parameter is not regarded

### ISSUE THREAD

**Issue by dshikhaleev** [pilosa/helm#2]
I tried to load test pilosa cluster in kubernetes. It works.
What was not clear is how many replicas pilosa maintains by default.
helm does not put replicas parameter into configuration. 
I tested pilosa as is; then I added replicas = 1 parameter and see no difference in performance;
Also, disks in all 3 containers contain almost equal amount of data.
Is replicas parameter regarded at all? 
Is it helm or pilosa server issue?

I test on GKE with 3 x n1-highcpu-32 (32 vCPUs, 28.8 GB memory) nodes.
My data volume is pretty small. du shows 500MB is used in each container.
I wonder if my data volume is too small to notice the difference.

**Comment by dshikhaleev** [comment]
then I changed replicas to 3 and see performance reduced by 40%..

**Comment by dshikhaleev** [comment]
I could observe the difference in performance with different number of replicas.

**Comment by jaffee** [comment]
replicas is inclusive, so minimum is one.
